add circleci
mattermost/mattermost-plugin-antivirus pull request #4
Opened 2019-03-01 15:00 UTC by cpanato

Based on the dev meeting we are moving to circleci

2019-03-04 13:57 UTC, hanzei requested changes
Let's wait until https://github.com/mattermost/mattermost-plugin-sample/pull/31 is approved and merged.

2019-03-06 12:56 UTC, cpanato commented
@hanzei PTAL

2019-03-06 15:31 UTC, crspeller approved these changes

2019-03-06 18:22 UTC, hanzei approved these changes

2019-03-06 18:22 UTC, merged